import { motion, AnimatePresence } from 'framer-motion';
import { BookOpen, Copy, Check, Download } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { useState } from 'react';

const StoryCard = ({ story }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(story);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <AnimatePresence>
      {story && (
        <motion.div
          initial={{ opacity: 0, y: 40, scale: 0.95 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: -20, scale: 0.95 }}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          style={{
            width: '100%',
            maxWidth: '800px',
            margin: '48px auto 0',
            padding: '0 24px',
          }}
        >
          {/* Card wrapper with gradient border */}
          <div
            style={{
              padding: '2px',
              borderRadius: '20px',
              background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.3), rgba(6, 182, 212, 0.15), rgba(139, 92, 246, 0.1))',
              animation: 'borderGlow 4s ease infinite',
            }}
          >
            <div
              style={{
                borderRadius: '18px',
                background: 'rgba(15, 13, 21, 0.95)',
                backdropFilter: 'blur(20px)',
                WebkitBackdropFilter: 'blur(20px)',
                overflow: 'hidden',
              }}
            >
              {/* Card Header */}
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  padding: '20px 28px',
                  borderBottom: '1px solid rgba(255, 255, 255, 0.06)',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <motion.div
                    animate={{ rotate: [0, -10, 10, 0] }}
                    transition={{ duration: 2, repeat: Infinity, repeatDelay: 3 }}
                    style={{
                      width: '36px',
                      height: '36px',
                      borderRadius: '10px',
                      background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.2), rgba(6, 182, 212, 0.2))',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                    }}
                  >
                    <BookOpen size={18} color="#d0bcff" />
                  </motion.div>
                  <div>
                    <h2
                      style={{
                        fontSize: '18px',
                        fontWeight: 700,
                        fontFamily: "'Inter', sans-serif",
                        letterSpacing: '-0.02em',
                        color: '#e7e0ed',
                      }}
                    >
                      Your Project's Story
                    </h2>
                    <p style={{ fontSize: '12px', color: '#6b6580', marginTop: '2px' }}>
                      Generated by AI • Powered by Groq
                    </p>
                  </div>
                </div>

                <div style={{ display: 'flex', gap: '8px' }}>
                  <motion.button
                    onClick={handleCopy}
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '6px',
                      padding: '8px 14px',
                      borderRadius: '8px',
                      border: '1px solid rgba(255, 255, 255, 0.08)',
                      background: 'rgba(255, 255, 255, 0.03)',
                      color: copied ? '#4cd7f6' : '#9b95a8',
                      fontSize: '12px',
                      fontWeight: 500,
                      cursor: 'pointer',
                      transition: 'all 0.3s',
                      fontFamily: "'Inter', sans-serif",
                    }}
                  >
                    {copied ? <Check size={14} /> : <Copy size={14} />}
                    {copied ? 'Copied!' : 'Copy'}
                  </motion.button>
                </div>
              </div>

              {/* Card Body - Story content */}
              <div
                style={{
                  padding: '28px',
                  fontSize: '15px',
                  lineHeight: 1.8,
                  color: '#cbc3d7',
                  fontFamily: "'Inter', sans-serif",
                }}
              >
                <div
                  className="story-content"
                  style={{
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '16px',
                  }}
                >
                  <ReactMarkdown
                    components={{
                      p: ({ children }) => (
                        <motion.p
                          initial={{ opacity: 0, x: -10 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ duration: 0.5 }}
                          style={{
                            fontSize: '15px',
                            lineHeight: 1.8,
                            color: '#cbc3d7',
                          }}
                        >
                          {children}
                        </motion.p>
                      ),
                      h1: ({ children }) => (
                        <h1 style={{ fontSize: '24px', fontWeight: 700, color: '#e7e0ed', marginBottom: '8px' }}>
                          {children}
                        </h1>
                      ),
                      h2: ({ children }) => (
                        <h2 style={{ fontSize: '20px', fontWeight: 600, color: '#e7e0ed', marginBottom: '8px' }}>
                          {children}
                        </h2>
                      ),
                      h3: ({ children }) => (
                        <h3 style={{ fontSize: '17px', fontWeight: 600, color: '#d0bcff', marginBottom: '6px' }}>
                          {children}
                        </h3>
                      ),
                      strong: ({ children }) => (
                        <strong style={{ color: '#e7e0ed', fontWeight: 600 }}>{children}</strong>
                      ),
                      em: ({ children }) => (
                        <em style={{ color: '#4cd7f6', fontStyle: 'italic' }}>{children}</em>
                      ),
                      code: ({ children }) => (
                        <code
                          style={{
                            background: 'rgba(139, 92, 246, 0.1)',
                            padding: '2px 8px',
                            borderRadius: '4px',
                            fontSize: '13px',
                            fontFamily: "'Space Grotesk', monospace",
                            color: '#d0bcff',
                          }}
                        >
                          {children}
                        </code>
                      ),
                      blockquote: ({ children }) => (
                        <blockquote
                          style={{
                            borderLeft: '3px solid rgba(139, 92, 246, 0.4)',
                            paddingLeft: '16px',
                            margin: '8px 0',
                            color: '#9b95a8',
                            fontStyle: 'italic',
                          }}
                        >
                          {children}
                        </blockquote>
                      ),
                    }}
                  >
                    {story}
                  </ReactMarkdown>
                </div>
              </div>

              {/* Card Footer */}
              <div
                style={{
                  padding: '16px 28px',
                  borderTop: '1px solid rgba(255, 255, 255, 0.04)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                }}
              >
                <p style={{ fontSize: '11px', color: '#4a4460', letterSpacing: '0.05em', textTransform: 'uppercase', fontWeight: 600 }}>
                  Generated Narrative
                </p>
                <div style={{
                  width: '40px',
                  height: '3px',
                  borderRadius: '2px',
                  background: 'linear-gradient(90deg, #8b5cf6, #06b6d4)',
                  opacity: 0.5,
                }} />
              </div>
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default StoryCard;